package-lock.json
package.json
src/components/AddressCard.vue
src/components/Territories.vue
src/components/Territory.vue
src/components/TerritoryCard.vue
src/main.js
src/store/index.js
src/store/modules/territory.js

1. allows user to mark addresses as "interested", "not interested", "not home", etc.
2. refactors some repeating html code into their own components.
3. moves some axios asynchronous calls to vuex pattern.

adds Publisher interaction to Address card

---

src/App.vue
src/components/AddressCard.vue
src/components/CheckoutModal.vue
src/components/Dnc.vue
src/components/Territories.vue
src/components/Territory.vue
src/components/TerritoryCard.vue
src/main.js
src/routes.js
src/store/index.js
src/store/modules/addresses.js
src/store/modules/territory.js

- adds more information to territory status (eg. publisher and date).
- adds DNC page and query

Enhanced status and dnc

---

.gitignore
package-lock.json
package.json
src/App.vue
src/components/Auth.vue
src/components/Masthead.vue
src/components/Signout.vue
src/components/Welcome.vue
src/firebase.config.js
src/main.js
src/routes.js
src/store/index.js
src/store/modules/auth.js
src/store/modules/territory.js

one of the benefits is persisted login.

login refactor to firebase

---

src/components/AddressCard.vue
src/main.js

I put it in a temporary location below the address. When we have the swipe-right panel, we can add it as a button there.

Adds 411 link to AddressCard

---

.travis.yml

Uses environment variables to store AWS secrets.  These env vars are configured in the Travis CI dashboard.

adds a simple deploy config to Travis CI

---

.ebextensions/00_change_npm_permissions.config

adds .ebextensions directory and a config file to set permissions for the nodejs user

fixes eb deploy errors

---

.ebextensions/00_change_npm_permissions.config
src/components/AddressCard.vue
src/components/AddressLinks.vue
src/routes.js

- replaces direct Google Maps link on address card
- allows multiple links for phone search

add AddressLinks component

---

src/components/AddressCard.vue
src/components/Territory.vue

Reverts rtercias/foreign-field#108

Revert "fix safari hidden address card on 2nd column"

---

.eslintrc
src/components/MyTerritory.vue
src/components/Territory.vue
src/components/Welcome.vue
src/store/modules/territory.js

add feature that lists territories recently seen in the welcome page

---

src/components/MyTerritory.vue
src/components/Territory.vue
src/components/Welcome.vue

- minor refactor of html content
- limit seen territories to last 5

Enhance welcome page

---

package-lock.json
package.json
src/components/ActivityHistory.vue
src/components/Masthead.vue
src/components/Optimize.vue
src/components/OptimizeCard.vue
src/components/Territory.vue
src/main.js
src/routes.js
src/store/modules/address.js
src/store/modules/addresses.js
src/store/modules/auth.js
src/store/modules/territory.js

Allows optimization of territory addresses. Also allows for manual sort override.

New feature: Optimize territory

---

src/components/CheckoutModal.vue
src/components/MyTerritory.vue
src/components/TerritoryCard.vue
src/store/modules/publishers.js
src/store/modules/territories.js

- fixed Publisher and Territory list sort order #132 
- also fixed missing last activity on dashboard #116

Fixed sort order on Publisher and Territory lists

---

src/components/MyTerritory.vue
src/components/Territory.vue
src/components/TerritoryCard.vue
src/store/modules/territories.js

minor refactor of the Territory and TerritoryCard components
- cleaned up Territory header
- reorganized Territory list - now showing City name first, then territory name
- made minor enhancements to checkin/checkout

Territory card facelift

---

src/components/Masthead.vue
src/components/Optimize.vue
src/components/TerritoryMap.vue
src/routes.js

allow elder roles to be able to manually sort addresses

---

src/components/Welcome.vue

This banner shows up just once, whenever someone opens the app. Then it doesn't show up again the next time they login.

adds a notification banner

---

src/components/Territory.vue
src/store/modules/territory.js

- renamed the reset button to "check in"
- added the vuex action 'checkinTerritory'
- added a router push into the home route after the territory is reset and checked in

changes reset button to check in

---

src/components/AddressTags.vue
src/components/Masthead.vue

1. #164 - adds a spinner while address tag is saving
2. adds a gold strip at the bottom of the masthead

adds spinner while address tag is saving

---

package-lock.json
src/components/Welcome.vue

Delete recent seen

---

src/components/AddressCard.vue
src/components/TerritoryAddresses.vue

automatically close sliding

---

src/components/AddressCard.vue
src/components/TerritoryAddresses.vue

Reverts rtercias/foreign-field#190

Revert "automatically close sliding"

---

src/components/AddressCard.vue
src/components/TerritoryAddresses.vue

Close slide

---

src/components/AddressForm.vue
src/components/AddressLinks.vue
src/components/PhoneAddressCard.vue
src/components/PhoneCard.vue
src/components/PhoneTags.vue
src/store/index.js
src/store/modules/phone.js

Moved the "Confirmed" button as a phone tag, instead of a status.
Created a new "Contacted" status.

Confirmed as tag

---

src/assets/foreign-field-theme.scss
src/components/ChangeLog.vue
src/components/PhoneAddressCard.vue
src/components/PhoneWitnessing.vue
src/components/SearchBar.vue
src/components/TerritoryAddresses.vue

adds SearchBar to Address and Phone modules

---

src/components/AddressTags.vue
src/components/MyTerritory.vue
src/components/Territory.vue
src/main.js
src/store/index.js
src/store/modules/auth.js

Add support for Cong options

---

src/components/ActivityButton.vue
src/components/AddressCard.vue
src/components/AddressTags.vue
src/components/PhoneAddressCard.vue
src/components/PhoneCard.vue
src/components/PhoneTags.vue
src/components/PhoneWitnessing.vue
src/components/Territory.vue
src/components/TerritoryAddresses.vue

Propagate "disabled" mode throughout Territory subcomponents.

Disabled mode

---

src/App.vue
src/components/AddressCard.vue
src/components/AddressForm.vue
src/components/AddressMap.vue
src/components/CongregationForm.vue
src/components/GroupForm.vue
src/components/Masthead.vue
src/components/Optimize.vue
src/components/OptimizeCard.vue
src/components/PhoneAddressCard.vue
src/components/PublisherForm.vue
src/components/Territories.vue
src/components/Territory.vue
src/components/TerritoryAddresses.vue
src/components/TerritoryForm.vue
src/main.js
src/routes.js
src/store/modules/address.js
src/store/modules/addresses.js
src/store/modules/auth.js
src/store/modules/group.js
src/store/modules/models/AddressModel.js
src/store/modules/models/RoleOptions.js
src/store/modules/phone.js
src/store/modules/territory.js

Brooklyn punch list

---

src/components/AddressForm.vue
src/components/AddressLinks.vue
src/components/AddressTags.vue
src/components/Change.vue
src/components/ChangeLog.vue
src/components/DNCReport.vue
src/components/PhoneAddressCard.vue
src/components/PublisherForm.vue
src/components/Reports.vue
src/components/SearchResults.vue
src/components/Territory.vue
src/routes.js
src/store/modules/address.js
src/store/modules/addresses.js
src/store/modules/models/AddressModel.js
src/store/modules/territory.js
src/utils/tags.js

Do not call

---

src/components/CheckoutModal.vue
src/components/Territories.vue
src/components/TerritoryCard.vue
src/store/modules/territories.js
src/store/modules/territory.js

Reverts rtercias/foreign-field#291

Revert "Fix reassign"

---

src/components/CheckoutModal.vue
src/components/Territories.vue
src/components/TerritoryCard.vue
src/store/modules/territories.js
src/store/modules/territory.js

Reverts rtercias/foreign-field#292

Revert "Revert "Fix reassign""

---

src/App.vue
src/components/AssignmentReport.vue
src/store/modules/reports.js

Added the following filters to S13:
- Campaign Mode
- Checkout Date
Also added a sort button.

add filters and sort for s13 report

---

package-lock.json
package.json

Reverts rtercias/foreign-field#311

Revert "Bump vue2-leaflet from 2.5.2 to 2.7.1"

---

src/App.vue
src/components/CheckoutModal.vue
src/components/Masthead.vue
src/components/NavMenu.vue

https://app.zenhub.com/workspaces/foreign-field-5ebe8254ac7c66a47195070c/issues/rtercias/foreign-field/329

Exclude inactive users from the app

---

src/App.vue
src/components/GroupsSelect.vue
src/components/MyTerritory.vue
src/components/NavMenu.vue
src/components/Territories.vue
src/components/Welcome.vue
src/store/modules/auth.js
src/store/modules/territories.js

https://github.com/rtercias/foreign-field/issues/331

Load territories page faster by fetching status and last activity asynchronously

---

src/components/GroupsSelect.vue
src/components/MyTerritory.vue
src/components/NavMenu.vue
src/components/Territories.vue
src/components/Welcome.vue
src/store/modules/auth.js
src/store/modules/territories.js

Reverts rtercias/foreign-field#332

Revert "Load territories page faster by fetching status and last activity asynchronously"

---

src/components/AddressForm.vue
src/components/AddressMap.vue
src/components/CheckoutModal.vue
src/components/GroupsSelect.vue
src/components/SearchResults.vue
src/store/modules/address.js
src/store/modules/territories.js
src/store/modules/territory.js

fixes bugs related to adding/updating addresses for a territory

---

package-lock.json
package.json

Reverts rtercias/foreign-field#459

Revert "Bump firebase from 7.24.0 to 9.16.0"

---

package-lock.json
src/components/ActivityLog.vue
src/components/Tags.vue
src/store/modules/address.js
src/store/modules/phone.js
src/store/modules/territory.js

- new phone number is missing 'Add Record' section
- set address first before making any updates

Prod fixes
